apiVersion: v1
kind: Service
metadata:
  name: sandcastle-realtime
  namespace: sandcastle
spec:
  selector:
    app: sandcastle-realtime
  ports:
    - name: http
      port: 4001
      targetPort: 4001
