apiVersion: batch/v1
kind: Job
metadata:
  name: sandcastle-seed
  namespace: sandcastle
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: ghcr.io/bolb/the-sandcastle-api:latest
          command: ["node", "dist/seed.js"]
          envFrom:
            - configMapRef:
                name: sandcastle-config
            - secretRef:
                name: sandcastle-secrets
  backoffLimit: 2
