"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { apiFetch } from "../../lib/api";
import { AuthCard, Field } from "../../components/auth-card";
import { Button } from "../../components/ui";

export default function LoginPage() {
  const router = useRouter();
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setPending(true);
    setError(null);

    const formData = new FormData(event.currentTarget);

    try {
      await apiFetch("/auth/login", {
        method: "POST",
        body: JSON.stringify({
          email: formData.get("email"),
          password: formData.get("password")
        })
      });
      router.push("/channels");
      router.refresh();
    } catch (nextError) {
      setError(nextError instanceof Error ? nextError.message : "Unable to sign in");
    } finally {
      setPending(false);
    }
  }

  return (
    <AuthCard title="Sign in" backHref="/channels">
      <form className="space-y-4" onSubmit={onSubmit}>
        <Field label="Email" name="email" type="email" placeholder="bolt@group.local" />
        <Field label="Password" name="password" type="password" placeholder="At least 12 characters" />
        {error ? <p className="text-sm text-rose-300">{error}</p> : null}
        <Button className="w-full" type="submit" disabled={pending}>
          {pending ? "Signing in..." : "Continue"}
        </Button>
      </form>
      <div className="mt-4 rounded-md border border-border bg-surface-raised px-4 py-3 text-sm text-ink-muted">
        Invite-only access. Password resets are generated by an owner or admin.
      </div>
    </AuthCard>
  );
}
